import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getMessages, getSessions } from "../api/chatbotapi";

export default function ChatHistory() {
  const [sessions, setSessions] = useState([]); const [messages, setMessages] = useState([]); const [error, setError] = useState("");
  useEffect(() => { const token = localStorage.getItem("token"); if (!token) return setError("Please sign in to view chat history."); getSessions(token).then(setSessions).catch(() => setError("Chat history is temporarily unavailable.")); }, []);
  const openSession = async (id) => { try { setMessages(await getMessages(id, localStorage.getItem("token"))); } catch { setError("Messages could not be loaded."); } };
  return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto grid max-w-5xl gap-6 md:grid-cols-3"><aside className="rounded-2xl bg-white p-5 shadow-sm"><Link to="/dashboard" className="text-sm font-medium text-cyan-700 hover:underline">← Dashboard</Link><h1 className="mt-4 text-2xl font-bold text-cyan-800">Chat History</h1>{error && <p className="mt-3 text-sm text-red-700">{error}</p>}<div className="mt-4 space-y-2">{sessions.map((session) => <button key={session.id} onClick={() => openSession(session.id)} className="w-full rounded-lg border p-3 text-left hover:bg-cyan-50"><strong className="block truncate">{session.title || "Conversation"}</strong><span className="text-xs text-slate-500">{new Date(session.created_at).toLocaleString()}</span></button>)}{!sessions.length && !error && <p className="text-sm text-slate-500">No saved conversations.</p>}</div></aside><section className="min-h-96 rounded-2xl bg-white p-6 shadow-sm md:col-span-2"><h2 className="text-xl font-semibold text-slate-800">Messages</h2>{messages.length ? <div className="mt-4 space-y-3">{messages.map((message) => <div key={message.id} className={`rounded-xl p-4 ${message.role === "user" ? "ml-10 bg-cyan-600 text-white" : "mr-10 bg-cyan-50 text-slate-800"}`}><strong>{message.role === "user" ? "You" : "AI"}</strong><p className="mt-1 whitespace-pre-wrap">{message.content}</p></div>)}</div> : <p className="mt-4 text-slate-500">Choose a conversation to view its messages.</p>}</section></div></main>;
}
