import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { askReportQuestion, getReports, ingestReport } from "../api/healthapi";

export default function HealthSummary() {
  const [reports, setReports] = useState([]); const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const [status, setStatus] = useState("");
  useEffect(() => { getReports().then(setReports).catch(() => setStatus("Could not load reports. Please sign in again.")); }, []);
  const indexReport = async (id) => { try { setStatus("Indexing report into vector database…"); const response = await ingestReport(id); setStatus(response.message || "Successfully indexed document for Q&A."); } catch (e) { setStatus(e.response?.data?.detail || "This report cannot be indexed yet. Make sure it contains text/OCR."); } };
  const ask = async (event) => { event.preventDefault(); if (!question.trim()) return; try { setStatus("Analyzing medical knowledge base…"); setAnswer(""); const response = await askReportQuestion(question); setAnswer(response.data?.answer || "No relevant information found."); setStatus(""); } catch (e) { setStatus(e.response?.data?.detail || "RAG is temporarily unavailable. Check backend logs or API keys."); } };
  return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-4xl"><Link to="/dashboard" className="text-sm font-medium text-cyan-700 hover:underline">← Dashboard</Link><h1 className="mt-3 text-3xl font-bold text-cyan-800">Health Summary & RAG</h1><p className="mt-2 text-slate-600">Index your medical reports, then ask AI questions grounded specifically in your own health documents.</p><section className="mt-6 rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Your reports</h2>{reports.length ? <ul className="mt-3 divide-y">{reports.map((report) => <li key={report.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><span><strong>{report.filename}</strong><span className="ml-2 text-sm text-slate-500">{report.category}</span></span><button onClick={() => indexReport(report.id)} className="rounded-md border border-cyan-600 bg-cyan-50 px-3 py-2 text-sm font-medium text-cyan-800 hover:bg-cyan-100 transition-colors">Index for Q&A</button></li>)}</ul> : <p className="mt-3 text-slate-500">No reports uploaded yet. <Link to="/upload-pdf" className="text-cyan-700 hover:underline">Upload one first.</Link></p>}</section><form onSubmit={ask} className="mt-6 rounded-2xl bg-white p-6 shadow-sm"><label className="font-semibold text-slate-800" htmlFor="health-question">Ask about your health reports (RAG)</label><div className="mt-3 flex gap-3"><input id="health-question" value={question} onChange={(e) => setQuestion(e.target.value)} placeholder="For example: What is my latest cholesterol level?" className="min-w-0 flex-1 rounded-lg border px-4 py-3 focus:outline-none focus:ring-2 focus:ring-cyan-500"/><button className="rounded-lg bg-cyan-600 px-6 font-semibold text-white hover:bg-cyan-700 transition-colors">Ask</button></div>{status && <div className="mt-4 flex items-center gap-2 text-amber-700 bg-amber-50 p-3 rounded-lg"><span className="animate-pulse">●</span> {status}</div>}{answer && <div className="mt-5 rounded-lg border border-cyan-100 bg-cyan-50/50 p-5 shadow-inner"><h3 className="font-semibold text-cyan-800 mb-2">AI Answer</h3><p className="whitespace-pre-wrap text-slate-700">{answer}</p></div>}</form></div></main>;
}
