import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { createReminder, deleteReminder, getReminders } from "../api/healthapi";

const initial = { title: "", time: "09:00", frequency: "daily", reminder_type: "medication", email_notification: true, is_active: true };
export default function Reminders() {
  const [timeHour, setTimeHour] = useState("09"); const [timeMinute, setTimeMinute] = useState("00");
  const load = async () => { try { setItems(await getReminders()); } catch { setMessage("Could not load reminders. Please sign in again."); } };
  useEffect(() => { load(); }, []);
  const submit = async (event) => { event.preventDefault(); setSaving(true); setMessage(""); try { const finalTime = `${timeHour}:${timeMinute}`; await createReminder({...form, time: finalTime}); setForm(initial); setTimeHour("09"); setTimeMinute("00"); setMessage("Reminder saved."); await load(); } catch (e) { setMessage(e.response?.data?.detail || "Reminder could not be saved."); } finally { setSaving(false); } };
  const remove = async (id) => { try { await deleteReminder(id); await load(); } catch { setMessage("Reminder could not be deleted."); } };
  return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-3xl"><Link to="/dashboard" className="text-sm font-medium text-cyan-700 hover:underline">← Dashboard</Link><h1 className="mt-3 text-3xl font-bold text-cyan-800">Medicine Reminders</h1><p className="mt-2 text-slate-600">Set a medicine name and time.</p><form onSubmit={submit} className="mt-6 grid gap-4 rounded-2xl bg-white p-6 shadow-sm md:grid-cols-2"><label>Medicine / reminder name<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="e.g. Vitamin D" className="mt-1 w-full rounded-lg border p-3"/></label><fieldset><legend className="mb-1 text-slate-700">Time</legend><div className="flex gap-2"><select value={timeHour} onChange={(e) => setTimeHour(e.target.value)} className="w-full rounded-lg border p-3">{Array.from({length:24}).map((_, i) => { const val = i.toString().padStart(2, '0'); return <option key={val} value={val}>{val}</option>; })}</select><span className="self-center text-xl">:</span><select value={timeMinute} onChange={(e) => setTimeMinute(e.target.value)} className="w-full rounded-lg border p-3"><option value="00">00</option><option value="15">15</option><option value="30">30</option><option value="45">45</option></select></div></fieldset><label>Frequency<select value={form.frequency} onChange={(e) => setForm({ ...form, frequency: e.target.value })} className="mt-1 w-full rounded-lg border p-3"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="once">Once</option></select></label><label>Type<select value={form.reminder_type} onChange={(e) => setForm({ ...form, reminder_type: e.target.value })} className="mt-1 w-full rounded-lg border p-3"><option value="medication">Medication</option><option value="appointment">Appointment</option><option value="checkup">Checkup</option></select></label><label className="flex items-center gap-2"><input type="checkbox" checked={form.email_notification} onChange={(e) => setForm({ ...form, email_notification: e.target.checked })}/> Email notification</label><button disabled={saving} className="rounded-lg bg-cyan-600 px-5 py-3 font-semibold text-white disabled:opacity-60">{saving ? "Saving…" : "Save reminder"}</button></form>{message && <p className="mt-4 rounded-lg bg-cyan-50 p-3 text-cyan-800">{message}</p>}<section className="mt-6 rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Saved reminders</h2>{items.length ? <ul className="mt-3 divide-y">{items.map((item) => <li key={item.id} className="flex items-center justify-between gap-4 py-3"><span><strong>{item.title}</strong><span className="ml-3 text-slate-600">{item.time} · {item.frequency}</span></span><button type="button" onClick={() => remove(item.id)} className="text-sm font-semibold text-red-600">Delete</button></li>)}</ul> : <p className="mt-3 text-slate-500">No reminders saved.</p>}</section></div></main>;
}
